Commit to Spring Boot Security Branch First
romaxa11/Online-Book-Store-App pull request #12
Opened 2023-09-15 18:42 UTC by romaxa11

2023-09-16 09:33 UTC, sokimaaa commented on src/main/java/mate/academy/intro/config/SecurityConfig.java
> +                                .authenticated())
just a suggestion: let's permit all to see 
1. /error - error page
2. /swagger-ui/** - documentation of your API.

2023-09-16 09:42 UTC, sokimaaa commented on src/main/java/mate/academy/intro/exception/RegistrationException.java
> +public class RegistrationException extends Exception {
let's make this exception extended from RuntimeException to reduce boilerplate code. 
```suggestion
public class RegistrationException extends RuntimeException {
```

2023-09-16 09:53 UTC, sokimaaa commented on src/main/java/mate/academy/intro/service/user/impl/UserServiceImpl.java
> +        }
You already have checked that password and repeatPassword are the same using @FieldMatch. 

```suggestion
```

2023-09-16 10:04 UTC, sokimaaa commented on src/main/java/mate/academy/intro/model/Role.java
> +@Data
@Data is not recommended for use with Entity.

2023-09-16 10:06 UTC, sokimaaa commented on src/main/java/mate/academy/intro/exception/RegistrationException.java
> +public class RegistrationException extends Exception {
make sure you handle this exception using GlobalHandler

2023-09-17 14:50 UTC, Rommelua requested changes

2023-09-17 14:50 UTC, Rommelua commented on src/main/java/mate/academy/intro/validation/Email.java
> +public @interface Email {
you do not use this annotation, so, you can delete it

2023-09-17 14:50 UTC, Rommelua commented on src/main/java/mate/academy/intro/model/User.java
> +@Data
@DaTa is not recommended for use with Entity.

2023-09-17 14:50 UTC, Rommelua commented on src/main/java/mate/academy/intro/validation/EmailValidator.java
> +public class EmailValidator implements ConstraintValidator<Email,String> {
you can delete this class as well

2023-09-18 08:05 UTC, Rommelua approved these changes

2023-09-18 08:05 UTC, Rommelua commented on src/main/java/mate/academy/intro/model/Book.java
> +@ToString
why do you need @ToString? delete it anywhere

2023-09-18 08:14 UTC, merged