Commit to spring-boot-practice-shopping-cart-branch First
romaxa11/Online-Book-Store-App pull request #14
Opened 2023-09-22 03:25 UTC by romaxa11

2023-09-22 09:32 UTC, Rommelua requested changes

2023-09-22 09:32 UTC, Rommelua commented on src/main/java/mate/academy/intro/dto/cartitem/CreateCartItemRequestDto.java
> +    @Min(0)
```suggestion
    @Min(1)
```

2023-09-22 09:32 UTC, Rommelua commented on src/main/java/mate/academy/intro/model/CartItem.java
> +    @Min(0)
```suggestion
    @Min(1)
```

2023-09-22 09:32 UTC, Rommelua commented on src/main/java/mate/academy/intro/model/ShoppingCart.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
```suggestion
```

2023-09-22 09:32 UTC, Rommelua commented on src/main/java/mate/academy/intro/model/ShoppingCart.java
> +    private User user;
```suggestion
    @OneToOne(cascade = CascadeType.ALL)
    @MapsId
    private User user;
```

2023-09-22 09:32 UTC, Rommelua commented on src/main/java/mate/academy/intro/repository/cartitem/CartItemRepository.java
> +    void deleteByShoppingCart_Id(Long shoppingCartId);
we should use soft delete

2023-09-23 15:31 UTC, aaananas approved these changes

2023-09-23 15:31 UTC, aaananas commented on src/main/java/mate/academy/intro/controller/ShoppingCartController.java
> +    @DeleteMapping("cart-items/{cartItemId}")
```suggestion
    @DeleteMapping("/cart-items/{cartItemId}")
```

2023-09-23 15:31 UTC, aaananas commented on src/main/java/mate/academy/intro/controller/ShoppingCartController.java
> +    @PutMapping("cart-items/{itemId}")
```suggestion
    @PutMapping("/cart-items/{itemId}")
```

2023-09-23 17:10 UTC, merged